# Denoising by Delaunay Triangulation on Spectrogram zeros

In [1]:
import numpy as np
import time
from numpy import pi as pi
import seaborn as sns
import matplotlib.pyplot as plt
import cmocean
from src.utilstf import *
from mcsm_benchs.Benchmark import Benchmark
from mcsm_benchs.SignalBank import SignalBank
from src.methods.method_delaunay_triangulation import delaunay_triangulation_denoising

In [2]:
# signal parameters
SNRin = 10
N = 512
sbank = SignalBank(N=N, return_signal=True)
tmin = sbank.tmin
tmax = sbank.tmax
s = sbank.signal_mc_damped_cos()

np.random.seed(0)
reps = 50
M = [512, 1024, 2048]
elapsed = np.zeros((len(M),reps))
qrf = np.zeros((len(M),reps))

for m in range(len(M)):
    for i in range(reps):
        noise = np.random.randn(N,)
        signal = Benchmark.sigmerge(s, noise, SNRin)
        start = time.time()
        output = delaunay_triangulation_denoising(signal,
                                        Nfft = M[m],
                                        grouping = True,
                                        ngroups=signal.total_comps,
                                        LB = 1.4,
                                        )

        end = time.time()
        elapsed[m,i] = end-start
        qrf[m,i] = Benchmark.snr_comparison(s,output,tmin=tmin,tmax=tmax)

In [3]:
np.mean(qrf,axis=1)

array([13.2921278 , 11.81010279,  4.3894649 ])

In [4]:
np.mean(elapsed,axis=1)

array([0.40140302, 0.63038939, 1.07652465])

In [5]:
# signal parameters
SNRin = 10
N = 1024
sbank = SignalBank(N=N, return_signal=True)
tmin = sbank.tmin
tmax = sbank.tmax
s = sbank.signal_mc_damped_cos()

np.random.seed(0)
reps = 50
M = [512, 1024, 2048]
elapsed = np.zeros((len(M),reps))
qrf = np.zeros((len(M),reps))

for m in range(len(M)):
    for i in range(reps):
        noise = np.random.randn(N,)
        signal = Benchmark.sigmerge(s, noise, SNRin)
        start = time.time()
        output = delaunay_triangulation_denoising(signal,
                                        Nfft = M[m],
                                        grouping = True,
                                        ngroups=signal.total_comps,
                                        LB = 1.45,
                                        )

        end = time.time()
        elapsed[m,i] = end-start
        qrf[m,i] = Benchmark.snr_comparison(s,output,tmin=tmin,tmax=tmax)

In [6]:
np.mean(qrf,axis=1)

array([14.67084195, 15.02584566, 14.5935183 ])

In [7]:
np.mean(elapsed,axis=1)

array([0.80351038, 1.2736675 , 2.17706817])